site_name: 'Тинькофф Инвестиции OpenAPI'
docs_dir: docs
repo_url: https://github.com/TinkoffCreditSystems/invest-openapi
theme:
  name: material
  language: 'ru'
  palette:
    primary: black
    accent: yellow
  # custom_dir: swagger-iu/

nav:
- Начало работы: index.md
- Авторизация: auth.md
- Окружения: env.md
- "Протокол: rest": rest.md
- "Протокол: streaming": marketdata.md
- HOW-TO:
  - "Работа с торговыми поручениями": orders.md
  - "Инструменты и котировки": faq_marketdata.md
- FAQ:
  - "Условия использования": faq_rules.md
  - Ошибки: faq_errors.md
  - Песочница: faq_sandbox.md
  - Мультисчета: faq_multiaccounts.md
